<h1>First Look Data with Pandas</h1>
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWkCG5kkVQwhKLSO8V_FR3YMBRUuflaPRaFiFnMQHI6pjyiKhLjwdKuSU&s=10" width="200" height="200">

In [1]:
import pandas as pd
import matplotlib as plt

In [2]:
df=pd.read_csv(r'C:\Users\Dell\Python_4th_Sem\numpyand pandas\pandas_intro_practice_500_rows.csv')

In [3]:
df.head()

,Employee_ID,Name,Age,City,Department,Salary,Product,Quantity,Rating,Joining_Year
0,35,Sneha,33.0,Butwal,HR,115111.0,Headphones,9,3.0,2018
1,183,Aayush,37.0,Bhaktapur,IT,28396.0,Keyboard,8,3.1,2019
2,86,Neha,32.0,Chitwan,IT,96376.0,Mouse,3,4.6,2020
3,274,Sabin,21.0,Dharan,Operations,52479.0,Webcam,5,4.3,2019
4,37,Maya,55.0,Kathmandu,IT,34862.0,Keyboard,9,1.1,2023

In [4]:
df.tail()

,Employee_ID,Name,Age,City,Department,Salary,Product,Quantity,Rating,Joining_Year
495,114,Nisha,28.0,Butwal,Marketing,90771.0,Headphones,3,2.0,2025
496,97,Riya,35.0,Dharan,Marketing,$43958,Tablet,4,4.7,2020
497,226,Raj,34.0,Bhaktapur,HR,87676.0,Keyboard,8,4.0,2023
498,215,Riya,33.0,Bhaktapur,Marketing,60537.0,Headphones,3,1.4,2021
499,58,Suman,46.0,Kathmandu,HR,134168.0,Tablet,7,4.6,2018

In [5]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'City', 'Department', 'Salary', 'Product',
       'Quantity', 'Rating', 'Joining_Year'],
      dtype='str')

In [6]:
df["Name"].head()

0       Sneha
1      Aayush
2        Neha
3      Sabin
4        Maya
Name: Name, dtype: str

In [8]:
df[["Name", "Age", "City"]].head()

       Name   Age       City
0     Sneha  33.0     Butwal
1    Aayush  37.0  Bhaktapur
2      Neha  32.0    Chitwan
3    Sabin   21.0     Dharan
4      Maya  55.0  Kathmandu

In [9]:
df[df["Age"]>30].head()

,Employee_ID,Name,Age,City,Department,Salary,Product,Quantity,Rating,Joining_Year
0,35,Sneha,33.0,Butwal,HR,115111.0,Headphones,9,3.0,2018
1,183,Aayush,37.0,Bhaktapur,IT,28396.0,Keyboard,8,3.1,2019
2,86,Neha,32.0,Chitwan,IT,96376.0,Mouse,3,4.6,2020
4,37,Maya,55.0,Kathmandu,IT,34862.0,Keyboard,9,1.1,2023
5,6,Raj,43.0,Bhaktapur,Operations,34116.0,Laptop,4,4.1,2019

In [16]:
df[(df["City"] == "Kathmandu") & (df["Product"] == "Keyboard")]

,Employee_ID,Name,Age,City,Department,Salary,Product,Quantity,Rating,Joining_Year
4,37,Maya,55.0,Kathmandu,IT,34862.0,Keyboard,9,1.1,2023
169,417,Ramesh,42.0,Kathmandu,Operations,140336.0,Keyboard,8,4.7,2019
192,420,Sabin,23.0,Kathmandu,Operations,147469.0,Keyboard,9,4.4,2025
228,36,Maya,37.0,Kathmandu,IT,68719.0,Keyboard,5,1.6,2025
300,29,Amit,30.0,Kathmandu,Marketing,35500.0,Keyboard,2,NaN,2021
308,371,Sita,45.0,Kathmandu,Marketing,99870.0,Keyboard,2,4.8,2025
373,257,Sabin,50.0,Kathmandu,Operations,26238.0,Keyboard,2,3.0,2024
439,159,Sabin,53.0,Kathmandu,Operations,69140.0,Keyboard,10,2.5,2020
457,412,Kiran,49.0,Kathmandu,IT,131584.0,Keyboard,1,4.4,2023

In [17]:
df.isnull().sum()

Employee_ID     0
Name            0
Age             6
City            5
Department      6
Salary          6
Product         0
Quantity        0
Rating          6
Joining_Year    0
dtype: int64

Clear a missing number

In [18]:
df["Age"]=df["Age"].fillna(df["Age"].median())

In [20]:
df[(df["Age"]>18) & (df["Age"]<60)].head()

,Employee_ID,Name,Age,City,Department,Salary,Product,Quantity,Rating,Joining_Year
0,35,Sneha,33.0,Butwal,HR,115111.0,Headphones,9,3.0,2018
1,183,Aayush,37.0,Bhaktapur,IT,28396.0,Keyboard,8,3.1,2019
2,86,Neha,32.0,Chitwan,IT,96376.0,Mouse,3,4.6,2020
3,274,Sabin,21.0,Dharan,Operations,52479.0,Webcam,5,4.3,2019
4,37,Maya,55.0,Kathmandu,IT,34862.0,Keyboard,9,1.1,2023

In [21]:
df["Age"].mean()

np.float64(39.444)

In [23]:
df["age"]=df["Age"].apply(lambda x: "Adult" if x>=18 else "Child")
print(df.head())

   Employee_ID      Name   Age       City  Department    Salary     Product  \
0           35     Sneha  33.0     Butwal          HR  115111.0  Headphones
1          183    Aayush  37.0  Bhaktapur          IT   28396.0    Keyboard
2           86      Neha  32.0    Chitwan          IT   96376.0       Mouse
3          274    Sabin   21.0     Dharan  Operations   52479.0      Webcam
4           37      Maya  55.0  Kathmandu          IT   34862.0    Keyboard

   Quantity  Rating  Joining_Year    age
0         9     3.0          2018  Adult
1         8     3.1          2019  Adult
2         3     4.6          2020  Adult
3         5     4.3          2019  Adult
4         9     1.1          2023  Adult

In [24]:
df["age"].value_counts()

age
Adult    500
Name: count, dtype: int64

In [25]:
df["Age"].median()

np.float64(38.0)

In [27]:
df["Rating"]=df["Rating"].fillna(df["Rating"].mean())
print(df.head())

   Employee_ID      Name   Age       City  Department    Salary     Product  \
0           35     Sneha  33.0     Butwal          HR  115111.0  Headphones
1          183    Aayush  37.0  Bhaktapur          IT   28396.0    Keyboard
2           86      Neha  32.0    Chitwan          IT   96376.0       Mouse
3          274    Sabin   21.0     Dharan  Operations   52479.0      Webcam
4           37      Maya  55.0  Kathmandu          IT   34862.0    Keyboard

   Quantity  Rating  Joining_Year    age
0         9     3.0          2018  Adult
1         8     3.1          2019  Adult
2         3     4.6          2020  Adult
3         5     4.3          2019  Adult
4         9     1.1          2023  Adult

In [29]:
df=df.dropna(subset=["Product", "City"])
print(df.head())

   Employee_ID      Name   Age       City  Department    Salary     Product  \
0           35     Sneha  33.0     Butwal          HR  115111.0  Headphones
1          183    Aayush  37.0  Bhaktapur          IT   28396.0    Keyboard
2           86      Neha  32.0    Chitwan          IT   96376.0       Mouse
3          274    Sabin   21.0     Dharan  Operations   52479.0      Webcam
4           37      Maya  55.0  Kathmandu          IT   34862.0    Keyboard

   Quantity  Rating  Joining_Year    age
0         9     3.0          2018  Adult
1         8     3.1          2019  Adult
2         3     4.6          2020  Adult
3         5     4.3          2019  Adult
4         9     1.1          2023  Adult

In [30]:
df.isnull().sum()

Employee_ID     0
Name            0
Age             0
City            0
Department      6
Salary          6
Product         0
Quantity        0
Rating          0
Joining_Year    0
age             0
dtype: int64

Deleting dupilcate

In [31]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Length: 495, dtype: bool

In [32]:
df[df.isnull().any(axis=1)]

,Employee_ID,Name,Age,City,Department,Salary,Product,Quantity,Rating,Joining_Year,age
68,83,Neha,23.0,Pokhara,HR,NaN,Mouse,5,3.6,2020,Adult
80,299,Ramesh,51.0,Lalitpur,Marketing,NaN,Headphones,7,2.5,2019,Adult
96,422,Rahul,25.0,Dharan,NaN,130022.0,Webcam,2,4.4,2025,Adult
108,472,Priya,31.0,Lalitpur,NaN,103908.0,Monitor,4,2.7,2023,Adult
188,268,Amit,30.0,Chitwan,NaN,43198.0,Headphones,5,2.1,2020,Adult
203,213,Nisha,51.0,Butwal,Sales,NaN,Headphones,5,1.5,2024,Adult
283,116,Ramesh,20.0,Biratnagar,NaN,41199.0,Webcam,6,3.7,2022,Adult
343,258,Aayush,26.0,Kathmandu,NaN,52710.0,Webcam,5,1.2,2019,Adult
372,325,Priya,31.0,Kathmandu,Marketing,NaN,Tablet,4,2.3,2024,Adult
377,443,Sita,52.0,Lalitpur,Sales,NaN,Tablet,2,2.4,2021,Adult
392,28,Nisha,38.0,Bhaktapur,NaN,100914.0,Laptop,6,1.2,2025,Adult
447,315,Aayush,28.0,Chitwan,Marketing,NaN,Printer,9,3.7,2025,Adult

In [33]:
df.duplicated(keep=False)

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Length: 495, dtype: bool

In [ ]:
df.drop_duplicates(inplace=True)

In [41]:
df["City"]=df["City"].str.strip().str.title()
print(df["City"].unique())

<StringArray>
[    'Butwal',  'Bhaktapur',    'Chitwan',     'Dharan',  'Kathmandu',
   'Lalitpur',    'Pokhara', 'Biratnagar']
Length: 8, dtype: str

In [42]:
df["Salary"]=df["Salary"].str.replace(",","").astype(float)

ValueError: could not convert string to float: '$110003'