<H1>DATASET OF THE BUSINESS FIRM AND THE DATA CLEANUNG</H1>

In [39]:
import pandas as pd

In [64]:
df=pd.read_csv("C:/Users/Dell/Python_4th_Sem/numpyand pandas/day_10_dataset.csv")

In [65]:
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Customer_Age,Gender,City,Province,Product_Category,Product_Name,...,Payment_Method,Order_Status,Delivery_Date,Sales_Channel,Customer_Segment,Return_Flag,Rating,Coupon_Code,Delivery_Days,Cost_NPR
0,ORD20250001,2025-03-04,CUST0175,Anup Lama,34.0,Male,Dhangadhi,Sudurpashchim,Fashion,Hoodie,...,Khalti,Delivered,2025-03-07,Daraz Marketplace,New,No,4.0,FREESHIP,3.0,1540
1,ORD20250002,2025-03-04,CUST0249,Ramesh Shrestha,47.0,Female,Kathmandu,Bagmati,Electronics,Wireless Earbuds,...,Bank Transfer,Delivered,08/03/2025,Website,New,No,5.0,FESTIVE15,4.0,8209
2,ORD20250003,2025-07-30,CUST0429,Aayush Rai,41.0,Female,Pokhara,Gandaki,Electronics,Bluetooth Speaker,...,Khalti,Delivered,02/08/2025,Mobile App,New,No,4.0,SAVE5,3.0,3024
3,ORD20250004,2025-07-13,CUST0064,Aashika Shrestha,21.0,Female,Biratnagar,Koshi,Beauty,Sunscreen SPF50,...,eSewa,failed,NaN,Mobile App,New,No,NaN,SAVE5,NaN,771
4,ORD20250005,2025-09-21,CUST0539,Sushma Lama,41.0,Female,Biratnagar,Koshi,Home & Kitchen,Storage Box Set,...,bank transfer,Delivered,2025-09-26,Mobile App,New,No,5.0,NEWUSER20,5.0,1605

In [67]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1818 entries, 0 to 1817
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          1818 non-null   str
 1   Order_Date        1818 non-null   str
 2   Customer_ID       1818 non-null   str
 3   Customer_Name     1798 non-null   str
 4   Customer_Age      1783 non-null   str
 5   Gender            1818 non-null   str
 6   City              1818 non-null   str
 7   Province          1818 non-null   str
 8   Product_Category  1818 non-null   str
 9   Product_Name      1818 non-null   str
 10  Quantity          1806 non-null   float64
 11  Unit_Price_NPR    1808 non-null   str
 12  Discount          1806 non-null   str
 13  Shipping_Fee_NPR  1818 non-null   str
 14  Payment_Method    1818 non-null   str
 15  Order_Status      1818 non-null   str
 16  Delivery_Date     1543 non-null   str
 17  Sales_Channel     1818 non-null   str
 18  Customer_Segment  1818 non-null   str
 19  Return_Flag       1818 non-null   str
 20  Rating            1549 non-null   str
 21  Coupon_Code       1519 non-null   str
 22  Delivery_Days     1550 non-null   str
 23  Cost_NPR          1810 non-null   str
dtypes: float64(1), str(23)
memory usage: 341.0 KB
None

In [68]:
print(df.shape)

(1818, 24)

In [69]:
print(df.describe())

          Quantity
count  1806.000000
mean      1.366002
std       0.712793
min      -1.000000
25%       1.000000
50%       1.000000
75%       2.000000
max       4.000000

In [70]:
print(df.isnull().sum())

Order_ID              0
Order_Date            0
Customer_ID           0
Customer_Name        20
Customer_Age         35
Gender                0
City                  0
Province              0
Product_Category      0
Product_Name          0
Quantity             12
Unit_Price_NPR       10
Discount             12
Shipping_Fee_NPR      0
Payment_Method        0
Order_Status          0
Delivery_Date       275
Sales_Channel         0
Customer_Segment      0
Return_Flag           0
Rating              269
Coupon_Code         299
Delivery_Days       268
Cost_NPR              8
dtype: int64

In [71]:
print(df.isnull())

      Order_ID  Order_Date  Customer_ID  Customer_Name  Customer_Age  Gender  \
0        False       False        False          False         False   False
1        False       False        False          False         False   False
2        False       False        False          False         False   False
3        False       False        False          False         False   False
4        False       False        False          False         False   False
...        ...         ...          ...            ...           ...     ...
1813     False       False        False          False         False   False
1814     False       False        False          False         False   False
1815     False       False        False          False         False   False
1816     False       False        False          False         False   False
1817     False       False        False          False         False   False

       City  Province  Product_Category  Product_Name  ...  Payment_Method  \
0     False     False             False         False  ...           False
1     False     False             False         False  ...           False
2     False     False             False         False  ...           False
3     False     False             False         False  ...           False
4     False     False             False         False  ...           False
...     ...       ...               ...           ...  ...             ...
1813  False     False             False         False  ...           False
1814  False     False             False         False  ...           False
1815  False     False             False         False  ...           False
1816  False     False             False         False  ...           False
1817  False     False             False         False  ...           False

      Order_Status  Delivery_Date  Sales_Channel  Customer_Segment  \
0            False          False          False             False
1            False          False          False             False
2            False          False          False             False
3            False           True          False             False
4            False          False          False             False
...            ...            ...            ...               ...
1813         False          False          False             False
1814         False           True          False             False
1815         False           True          False             False
1816         False          False          False             False
1817         False          False          False             False

      Return_Flag  Rating  Coupon_Code  Delivery_Days  Cost_NPR
0           False   False        False          False     False
1           False   False        False          False     False
2           False   False        False          False     False
3           False    True        False           True     False
4           False   False        False          False     False
...           ...     ...          ...            ...       ...
1813        False   False        False          False     False
1814        False    True        False           True     False
1815        False    True        False           True     False
1816        False   False         True          False     False
1817        False   False        False          False     False

[1818 rows x 24 columns]

In [72]:
print(df.isnull().sum())

Order_ID              0
Order_Date            0
Customer_ID           0
Customer_Name        20
Customer_Age         35
Gender                0
City                  0
Province              0
Product_Category      0
Product_Name          0
Quantity             12
Unit_Price_NPR       10
Discount             12
Shipping_Fee_NPR      0
Payment_Method        0
Order_Status          0
Delivery_Date       275
Sales_Channel         0
Customer_Segment      0
Return_Flag           0
Rating              269
Coupon_Code         299
Delivery_Days       268
Cost_NPR              8
dtype: int64

In [24]:
print(df.isnull().sum())

Order_ID              0
Order_Date            0
Customer_ID           0
Customer_Name         0
Customer_Age          0
Gender                0
City                  0
Province              0
Product_Category      0
Product_Name          0
Quantity             12
Unit_Price_NPR       10
Discount             12
Shipping_Fee_NPR      0
Payment_Method        0
Order_Status          0
Delivery_Date       275
Sales_Channel         0
Customer_Segment      0
Return_Flag           0
Rating              269
Coupon_Code         299
Delivery_Days       268
Cost_NPR              8
dtype: int64

In [26]:
df["Quantity"] = df["Quantity"].fillna(
    df["Quantity"].median()
)
print(df["Quantity"])

0       1.0
1       4.0
2       1.0
3       1.0
4       2.0
       ...
1813    2.0
1814    2.0
1815    1.0
1816    1.0
1817    1.0
Name: Quantity, Length: 1818, dtype: float64

In [27]:
df["Quantity"].isnull().sum()

np.int64(0)

In [28]:
df.isnull().sum()

Order_ID              0
Order_Date            0
Customer_ID           0
Customer_Name         0
Customer_Age          0
Gender                0
City                  0
Province              0
Product_Category      0
Product_Name          0
Quantity              0
Unit_Price_NPR       10
Discount             12
Shipping_Fee_NPR      0
Payment_Method        0
Order_Status          0
Delivery_Date       275
Sales_Channel         0
Customer_Segment      0
Return_Flag           0
Rating              269
Coupon_Code         299
Delivery_Days       268
Cost_NPR              8
dtype: int64

In [40]:
df["Unit_Price_NPR"] = pd.to_numeric(
    df["Unit_Price_NPR"], errors="coerce"
)

df["Unit_Price_NPR"] = df["Unit_Price_NPR"].fillna(
    df["Unit_Price_NPR"].median()
)

print(df["Unit_Price_NPR"])

0       2490.0
1       2570.0
2       4650.0
3       1460.0
4       1480.0
         ...
1813    2590.0
1814    2570.0
1815    4590.0
1816    3020.0
1817    2980.0
Name: Unit_Price_NPR, Length: 1818, dtype: float64

In [41]:
df.isnull().sum()

Order_ID              0
Order_Date            0
Customer_ID           0
Customer_Name         0
Customer_Age          0
Gender                0
City                  0
Province              0
Product_Category      0
Product_Name          0
Quantity              0
Unit_Price_NPR        0
Discount             12
Shipping_Fee_NPR      0
Payment_Method        0
Order_Status          0
Delivery_Date       275
Sales_Channel         0
Customer_Segment      0
Return_Flag           0
Rating              269
Coupon_Code         299
Delivery_Days       268
Cost_NPR              8
dtype: int64

In [42]:
df["Discount"] = pd.to_numeric(
    df["Discount"], errors="coerce"
)

df["Discount"] = df["Discount"].fillna(
    df["Discount"].median()
)

print(df["Discount"])

0       0.00
1       0.10
2       0.05
3       0.05
4       0.20
        ...
1813    0.05
1814    0.15
1815    0.10
1816    0.00
1817    0.10
Name: Discount, Length: 1818, dtype: float64

In [43]:
df.isnull().sum()

Order_ID              0
Order_Date            0
Customer_ID           0
Customer_Name         0
Customer_Age          0
Gender                0
City                  0
Province              0
Product_Category      0
Product_Name          0
Quantity              0
Unit_Price_NPR        0
Discount              0
Shipping_Fee_NPR      0
Payment_Method        0
Order_Status          0
Delivery_Date       275
Sales_Channel         0
Customer_Segment      0
Return_Flag           0
Rating              269
Coupon_Code         299
Delivery_Days       268
Cost_NPR              8
dtype: int64

In [44]:
df[df["Delivery_Date"].isna()][
    ["Order_Status", "Order_Date", "Delivery_Date"]
].head(20)

    Order_Status   Order_Date Delivery_Date
3         failed   2025-07-13           NaN
5      Cancelled   2025-03-28           NaN
25       Pending   2025-04-13           NaN
27       Pending   2025-07-29           NaN
29        Failed   2025-07-04           NaN
30     Cancelled   2025-12-06           NaN
37        Failed   2025-04-08           NaN
44       Pending   2025-10-22           NaN
49       Pending   2025-03-20           NaN
50        Failed   2025-01-04           NaN
53       Pending   2025-01-15           NaN
58        Failed  05-Apr-2025           NaN
72     Cancelled   2025-02-10           NaN
75     Cancelled   2025-09-14           NaN
81       Pending   2025-06-06           NaN
85       Pending   2025-11-20           NaN
95     Cancelled   2025-01-10           NaN
97     Cancelled   2025-06-13           NaN
103    Cancelled   27/02/2025           NaN
112      Pending   2025-05-10           NaN

In [48]:
df["Order_Date"] = pd.to_datetime(
    df["Order_Date"],
    errors="coerce"
)

df["Delivery_Date"] = pd.to_datetime(
    df["Delivery_Date"],
    errors="coerce"
)
print(df[["Order_Date", "Delivery_Date"]].head(20))

   Order_Date Delivery_Date
0  2025-03-04    2025-03-07
1  2025-03-04           NaT
2  2025-07-30           NaT
3  2025-07-13           NaT
4  2025-09-21    2025-09-26
5  2025-03-28           NaT
6         NaT           NaT
7  2025-10-18    2025-10-22
8  2025-08-11           NaT
9  2025-07-16           NaT
10 2025-09-13           NaT
11 2025-08-03           NaT
12 2025-12-25    2025-12-28
13 2025-05-08           NaT
14 2025-03-28           NaT
15 2025-06-22    2027-01-15
16        NaT           NaT
17 2025-08-15    2025-08-16
18 2025-08-27           NaT
19        NaT    2025-07-25

In [49]:
df.tail(20)

,Order_ID,Order_Date,Customer_ID,Customer_Name,Customer_Age,Gender,City,Province,Product_Category,Product_Name,...,Payment_Method,Order_Status,Delivery_Date,Sales_Channel,Customer_Segment,Return_Flag,Rating,Coupon_Code,Delivery_Days,Cost_NPR
1798,ORD20251799,2025-05-14,CUST0468,Suraj Gurung,38.0,Male,Birgunj,Madhesh,Groceries,Coffee Beans 500g,...,Cash on Delivery,Delivered,NaT,Daraz Marketplace,Returning,No,5.0,FREESHIP,1.0,729
1799,ORD20251800,NaT,CUST0263,Anup Karki,18.0,Female,Dhangadhi,Sudurpashchim,Home & Kitchen,Non-Stick Pan,...,eSewa,Cancelled,NaT,website,Returning,No,NaN,FESTIVE15,NaN,1010
1800,ORD20250973,NaT,CUST0427,Bibek Joshi,23.0,Male,Bharatpur,Bagmati,Groceries,Green Tea 250g,...,Cash on Delivery,Delivered,NaT,Website,Returning,No,3.0,WELCOME10,1.0,396
1801,ORD20251092,2025-11-24,CUST0253,Anisha Joshi,51.0,Female,Biratnagar,Koshi,Fashion,Hoodie,...,Bank Transfer,Delivered,NaT,Daraz Marketplace,New,No,4.0,NEWUSER20,1.0,1528
1802,ORD20251375,2025-08-30,CUST0639,Bibek Magar,20.0,Male,Birgunj,Madhesh,Book,Python Programming Book,...,Cash on Delivery,Delivered,NaT,Mobile App,Returning,no,5.0,No Coupon,1.0,911
1803,ORD20250977,2025-09-07,CUST0313,Riya Rai,39.0,Female,Butwal,Lumbini,Books,Data Analytics Handbook,...,eSewa,Cancelled,NaT,Mobile App,Returning,No,NaN,WELCOME10,NaN,1262
1804,ORD20250487,2025-07-10,CUST0423,Riya Joshi,29.0,Male,Dhangadhi,Sudurpashchim,Electronics,Bluetooth Speaker,...,Cash on Delivery,Delivered,2025-07-14,Website,Returning,No,3.0,SAVE_5,4.0,3079
1805,ORD20250231,2025-07-02,CUST0344,Pooja Shrestha,27.0,Other,Kathmandu,Bagmati,Fashion,Running Shoes,...,Cash on Delivery,Delivered,NaT,Web,New,No,2.0,FESTIVE15,1.0,3272
1806,ORD20251798,NaT,CUST0006,Anup Tamang,29.0,Other,Pokhara,Gandaki,Groceries,Coffee Beans 500g,...,eSewa,Delivered,NaT,Instagram,Returning,No,4.0,WELCOME10,2.0,722
1807,ORD20251434,2025-12-02,CUST0464,Rohan Tamang,33.0,Other,Biratnagar,KOSHI,Groceries,Chocolate Pack,...,eSewa,Delivered,NaT,Daraz Marketplace,Returning,No,4.0,FESTIVE15,3.0,522
1808,ORD20251643,2025-05-21,CUST0154,Bibek Karki,34.0,Female,Nepalgunj,Lumbini,fashion,Running Shoes,...,Bank Transfer,Delivered,NaT,Website,Returning,No,2.0,WELCOME10,1.0,3128
1809,ORD20251314,NaT,CUST0372,Samir Shrestha,36.0,Other,Dharan,Koshi,Fashion,Denim Jeans,...,Bank Transfer,Delivered,NaT,Instagram,Returning,No,5.0,FESTIVE15,2.0,2014
1810,ORD20251290,NaT,CUST0318,Nisha Tamang,29.0,Other,Bhaktapur,Bagmati,Electronics,Bluetooth Speaker,...,Cash on Delivery,Delivered,NaT,Mobile App,New,No,5.0,No Coupon,3.0,3120
1811,ORD20251417,2025-09-05,CUST0292,Deepa Joshi,27.0,Male,Pokhara,Gandaki,Electronics,Power Bank 20000mAh,...,Bank Transfer,Delivered,NaT,Website,Returning,No,4.0,NEWUSER20,2.0,3666
1812,ORD20250932,2025-06-20,CUST0275,Ujjwal Magar,23.0,Female,Biratnagar,Koshi,Groceries,Chocolate Pack,...,esewa,Delivered,NaT,Mobile App,Returning,No,2.0,FREESHIP,7.0,532
1813,ORD20250562,2025-10-09,CUST0556,Kiran Thapa,28.0,Male,Dhangadhi,Sudurpashchim,Electronics,Power Bank 20000mAh,...,Khalti,Delivered,2025-10-10,Mobile App,Returning,No,5.0,WELCOME10,1.0,3301
1814,ORD20251117,2025-03-07,CUST0583,Anisha Gurung,37.0,Male,Hetauda,Bagmati,Electronics,Bluetooth Speaker,...,Bank Transfer,Failed,NaT,Mobile App,Returning,No,NaN,FREESHIP,NaN,5655
1815,ORD20250705,NaT,CUST0015,Sushma Karki,18.0,Female,Nepalgunj,Lumbini,Electronics,Bluetooth Speaker,...,Cash on Delivery,Cancelled,NaT,Website,Returning,No,NaN,SAVE5,NaN,3005
1816,ORD20250666,2025-12-17,CUST0259,Deepa Adhikari,35.0,Male,Butwal,Lumbini,Electronics,Power Bank 20000mAh,...,eSewa,Delivered,NaT,Daraz Marketplace,Returning,No,1.0,No Coupon,1.0,1765
1817,ORD20250712,NaT,CUST0499,Kritika Magar,24.0,Other,Bhaktapur,Bagmati,Electronics,Power Bank 20000mAh,...,cash on delivery,Delivered,NaT,Instagram,Returning,no,4.0,NEWUSER20,4.0,1763

In [ ]:
print(df["Delivery_Date"].isna().sum())

1258

In [ ]:
df["Coupon_Code"] = df["Coupon_Code"].fillna("No Coupon")

In [50]:
df.isnull().sum()

Order_ID               0
Order_Date           442
Customer_ID            0
Customer_Name          0
Customer_Age           0
Gender                 0
City                   0
Province               0
Product_Category       0
Product_Name           0
Quantity               0
Unit_Price_NPR         0
Discount               0
Shipping_Fee_NPR       0
Payment_Method         0
Order_Status           0
Delivery_Date       1258
Sales_Channel          0
Customer_Segment       0
Return_Flag            0
Rating               269
Coupon_Code            0
Delivery_Days        268
Cost_NPR               8
dtype: int64

In [51]:
df["Order_Date"].head()

0   2025-03-04
1   2025-03-04
2   2025-07-30
3   2025-07-13
4   2025-09-21
Name: Order_Date, dtype: datetime64[us]

In [52]:
df["Order_Date"].dtype

dtype('<M8[us]')

In [53]:
df["Order_Date"].head()

0   2025-03-04
1   2025-03-04
2   2025-07-30
3   2025-07-13
4   2025-09-21
Name: Order_Date, dtype: datetime64[us]

In [54]:
df["Delivery_Date"].head()

0   2025-03-07
1          NaT
2          NaT
3          NaT
4   2025-09-26
Name: Delivery_Date, dtype: datetime64[us]

In [55]:
df["Delivery_Date"].dtype

dtype('<M8[us]')

In [56]:
df["Delivery_Date"].isnull().sum()

np.int64(1258)

In [57]:
df["Delivery_Days"].head()

0    3.0
1    4.0
2    3.0
3    NaN
4    5.0
Name: Delivery_Days, dtype: str

In [58]:
df["Delivery_Days"].isnull().sum()

np.int64(268)

In [59]:
df.isnull().sum()

Order_ID               0
Order_Date           442
Customer_ID            0
Customer_Name          0
Customer_Age           0
Gender                 0
City                   0
Province               0
Product_Category       0
Product_Name           0
Quantity               0
Unit_Price_NPR         0
Discount               0
Shipping_Fee_NPR       0
Payment_Method         0
Order_Status           0
Delivery_Date       1258
Sales_Channel          0
Customer_Segment       0
Return_Flag            0
Rating               269
Coupon_Code            0
Delivery_Days        268
Cost_NPR               8
dtype: int64